### ISSUE TITLE
Unable to install in windows, similar 'Failed building wheel for fitsne' as in previous issues

### ISSUE THREAD

**Issue by adpala** [KlugerLab/pyFIt-SNE#12]
Here is the terminal output. I have already vs build tools v14.0, as suggested in previous terminal output errors. This output I copy here is from the 'pip install fitsne', but also fails in the same way when running 'python setup.py install'. I do make sure that pip is calling the .exe file from my specific environment. 

(leap) Z:\#Common\adrian\Workspace\python_scripts\pyFIt-SNE>pip install fitsne
Collecting fitsne
  Using cached https://files.pythonhosted.org/packages/b6/84/7f8ea3c3837228ed6eb4f2773e764443e4a92d4e5ffd4f6e85517def667e/fitsne-1.0.1.tar.gz
Requirement already satisfied: numpy in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\lib\site-packages (from fitsne) (1.15.4)
Requirement already satisfied: cython in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\lib\site-packages (from fitsne) (0.29.1)
Building wheels for collected packages: fitsne
  Running setup.py bdist_wheel for fitsne ... error
  Complete output from command c:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\apalaci\\AppData\\Local\\Temp\\pip-install-wag2_1al\\fitsne\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\apalaci\AppData\Local\Temp\pip-wheel-hb3z8zem --python-tag cp36:
  Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\fitsne
  copying fitsne\cywrap.py -> build\lib.win-amd64-3.6\fitsne
  copying fitsne\_version.py -> build\lib.win-amd64-3.6\fitsne
  copying fitsne\__init__.py -> build\lib.win-amd64-3.6\fitsne
  running build_ext
  building 'fitsne.cppwrap' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\fitsne
  creating build\temp.win-amd64-3.6\Release\fitsne\src
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ifitsne -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpfitsne/cppwrap.cpp /Fobuild\temp.win-amd64-3.6\Release\fitsne/cppwrap.obj -std=c++11 -O3 -pthread -lfftw3 -lm
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  cl : Command line warning D9002 : ignoring unknown option '-pthread'
  cl : Command line warning D9002 : ignoring unknown option '-lfftw3'
  cl : Command line warning D9002 : ignoring unknown option '-lm'
  cppwrap.cpp
  fitsne/cppwrap.cpp(234): warning C4804: '/': unsafe use of type 'bool' in operation
  fitsne/cppwrap.cpp(2541): error C2466: cannot allocate an array of constant size 0
  fitsne/cppwrap.cpp(2541): error C2133: '__pyx_t_8': unknown size
  Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'fitsne.cppwrap' extension
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ifitsne -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpfitsne/cppwrap.cpp /Fobuild\temp.win-amd64-3.6\Release\fitsne/cppwrap.obj -std=c++11 -O3 -pthread -lfftw3 -lm -stdlib=libc++
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  cl : Command line warning D9002 : ignoring unknown option '-pthread'
  cl : Command line warning D9002 : ignoring unknown option '-lfftw3'
  cl : Command line warning D9002 : ignoring unknown option '-lm'
  cl : Command line warning D9002 : ignoring unknown option '-stdlib=libc++'
  cppwrap.cpp
  fitsne/cppwrap.cpp(234): warning C4804: '/': unsafe use of type 'bool' in operation
  fitsne/cppwrap.cpp(2541): error C2466: cannot allocate an array of constant size 0
  fitsne/cppwrap.cpp(2541): error C2133: '__pyx_t_8': unknown size
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for fitsne
  Running setup.py clean for fitsne
Failed to build fitsne
Installing collected packages: fitsne
  Running setup.py install for fitsne ... error
    Complete output from command c:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\apalaci\\AppData\\Local\\Temp\\pip-install-wag2_1al\\fitsne\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\apalaci\AppData\Local\Temp\pip-record-u49d38h1\install-record.txt --single-version-externally-managed --compile:
    Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\fitsne
    copying fitsne\cywrap.py -> build\lib.win-amd64-3.6\fitsne
    copying fitsne\_version.py -> build\lib.win-amd64-3.6\fitsne
    copying fitsne\__init__.py -> build\lib.win-amd64-3.6\fitsne
    running build_ext
    building 'fitsne.cppwrap' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\fitsne
    creating build\temp.win-amd64-3.6\Release\fitsne\src
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ifitsne -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpfitsne/cppwrap.cpp /Fobuild\temp.win-amd64-3.6\Release\fitsne/cppwrap.obj -std=c++11 -O3 -pthread -lfftw3 -lm
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-pthread'
    cl : Command line warning D9002 : ignoring unknown option '-lfftw3'
    cl : Command line warning D9002 : ignoring unknown option '-lm'
    cppwrap.cpp
    fitsne/cppwrap.cpp(234): warning C4804: '/': unsafe use of type 'bool' in operation
    fitsne/cppwrap.cpp(2541): error C2466: cannot allocate an array of constant size 0
    fitsne/cppwrap.cpp(2541): error C2133: '__pyx_t_8': unknown size
    Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
    running install
    running build
    running build_py
    running build_ext
    building 'fitsne.cppwrap' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ifitsne -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include -Ic:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpfitsne/cppwrap.cpp /Fobuild\temp.win-amd64-3.6\Release\fitsne/cppwrap.obj -std=c++11 -O3 -pthread -lfftw3 -lm -stdlib=libc++
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-pthread'
    cl : Command line warning D9002 : ignoring unknown option '-lfftw3'
    cl : Command line warning D9002 : ignoring unknown option '-lm'
    cl : Command line warning D9002 : ignoring unknown option '-stdlib=libc++'
    cppwrap.cpp
    fitsne/cppwrap.cpp(234): warning C4804: '/': unsafe use of type 'bool' in operation
    fitsne/cppwrap.cpp(2541): error C2466: cannot allocate an array of constant size 0
    fitsne/cppwrap.cpp(2541): error C2133: '__pyx_t_8': unknown size
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\leap\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\apalaci\\AppData\\Local\\Temp\\pip-install-wag2_1al\\fitsne\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\apalaci\AppData\Local\Temp\pip-record-u49d38h1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\apalaci\AppData\Local\Temp\pip-install-wag2_1al\fitsne\

**Comment by mahdi-abdelkebir** [comment]
How was this solved???

**Comment by saw-a-bird** [comment]
How was this solved???
