### ISSUE TITLE
Missing df parameter

### ISSUE THREAD

**Issue by GWW** [KlugerLab/pyFIt-SNE#13]
Hi,

It appears the `df` parameter shown in the FIt-SNE [example notebook](https://github.com/KlugerLab/FIt-SNE/blob/master/examples/test.ipynb) is missing from the python wrapper.  I am not sure if it would be difficult to add this feature as it looks quite useful.

Thanks

**Comment by linqiaozhi** [comment]
This repo corresponds to the PyPI fitsne [package](https://pypi.org/project/fitsne/), which has not yet been updated to 1.1.0, so it does not yet support variable degrees of freedom. However, the main FIt-SNE [repository](https://github.com/KlugerLab/FIt-SNE) does have a Python wrapper that you can use in the interim, which does support `df`. The example notebook you linked to uses that wrapper.

**Comment by GWW** [comment]
Hi,

Thanks for the quick reply.  I assumed (incorrectly it seems) it was just a wrapper over the FIt-SNE C++ library and it would simply be adding a parameter.
