### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ccshao** [KlugerLab/pyFIt-SNE#15]
I followed the instruction (with miniconda) in the webpage https://pypi.org/project/fitsne/
but still could not install fitsne. 

I have tried both gcc-7 and gcc-8 on a linuxmint machine. FFTW installed.

The major error is (I think) 

> gcc: error: unrecognized command line option ‘-stdlib=libc++’

while the full error log
```

  ERROR: Complete output from command /home/XXX/miniconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9dhds9j9/fitsne/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xlep26va --python-tag cp37:
  ERROR: Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/fitsne
  copying fitsne/_version.py -> build/lib.linux-x86_64-3.7/fitsne
  copying fitsne/__init__.py -> build/lib.linux-x86_64-3.7/fitsne
  copying fitsne/cywrap.py -> build/lib.linux-x86_64-3.7/fitsne
  running build_ext
  building 'fitsne.cppwrap' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/fitsne
  creating build/temp.linux-x86_64-3.7/fitsne/src
  gcc -pthread -B /home/XXX/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifitsne -I/home/shao/miniconda3/include/python3.7m -c fitsne/cppwrap.cpp -o build/temp.linux-x86_64-3.7/fitsne/cppwrap.o -std=c++11 -O3 -pthread -lfftw3 -lm
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/XXX/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifitsne -I/home/XXX/miniconda3/include/python3.7m -c fitsne/src/nbodyfft.cpp -o build/temp.linux-x86_64-3.7/fitsne/src/nbodyfft.o -std=c++11 -O3 -pthread -lfftw3 -lm
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from fitsne/src/nbodyfft.cpp:4:
  fitsne/src/nbodyfft.h:7:10: fatal error: fftw3.h: No such file or directory
   #include <fftw3.h>
            ^~~~~~~~~
  compilation terminated.
  Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'fitsne.cppwrap' extension
  gcc -pthread -B /home/XXX/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifitsne -I/home/XXX/miniconda3/include/python3.7m -c fitsne/cppwrap.cpp -o build/temp.linux-x86_64-3.7/fitsne/cppwrap.o -std=c++11 -O3 -pthread -lfftw3 -lm -stdlib=libc++
  gcc: error: unrecognized command line option ‘-stdlib=libc++’
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fitsne

```

**Comment by florian-huber** [comment]
Got the same error (both on a linux and on a windows machine). 
Would that be due to this ? :
```
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s) 
```

**Comment by whitews** [comment]
Same error here. @florian-huber @ccshao did either of you figure out how to install?

**Comment by florian-huber** [comment]
@whitews : no, I wasn't able to install. Started looking at other t-sne implementations but that's going slow... I will give an update if I find something that works for me.

**Comment by ccshao** [comment]
I built the fit-tsne instead, see https://github.com/KlugerLab/FIt-SNE. 
If everything works, there should be a binary exec file, which should be put into a folder contained by PATH. Then seurat is able to find and use it. Good luck.

**Comment by JBreunig** [comment]
same issue here on Ubuntu

**Comment by farouktif** [comment]
> @whitews : no, I wasn't able to install. Started looking at other t-sne implementations but that's going slow... I will give an update if I find something that works for me.

did you manage to fix this issue? it have been trying for a couple of day and no luck so far :(

**Comment by whitews** [comment]
@farouktif Nope, we moved on to tsne-cuda:

https://github.com/CannyLab/tsne-cuda

**Comment by linqiaozhi** [comment]
I will look into this in further detail as soon as I can--sorry for the delays. 

Until then, please consider using the Python wrapper here:
https://github.com/KlugerLab/FIt-SNE

It's not a package (i.e. not installed by pip), but works very well.

**Comment by JBreunig** [comment]
I got the same errors with Flt-SNE install in Ubuntu.  Thanks in advance for looking into this.

**Comment by linqiaozhi** [comment]
@JBreunig Just take a quick look and see if this commit fixed your problem. @dkobak also reported problems with a new install on Ubuntu, looks like he resolved it.

https://github.com/KlugerLab/FIt-SNE/issues/81

**Comment by dkobak** [comment]
@linqiaozhi The errors shown in the first message in this thread look rather unrelated to what I fixed there...

**Comment by JBreunig** [comment]
> @JBreunig Just take a quick look and see if this commit fixed your problem. @dkobak also reported problems with a new install on Ubuntu, looks like he resolved it.
> 
> [KlugerLab/FIt-SNE#81](https://github.com/KlugerLab/FIt-SNE/issues/81)

I was able to compile and use the new commit.  Thanks!!  

(Had no luck again with fitsne before that though I had previously used it on another Ubuntu workstation and Windows.  But no need for it anyway since your installation instructions worked fine.)

**Comment by dkobak** [comment]
@JBreunig Just to clarify: do you mean that you managed to run FIt-SNE with a Python wrapper, or did you somehow integrate that commit 81 into the pyFIt-SNE and managed to run pyFIt-SNE?

**Comment by JBreunig** [comment]
Sorry for the typo above (fixed), I compiled it and it ran fine from Python.  I had tried before that to install fitsne again with no luck.

**Comment by linqiaozhi** [comment]
I updated pyFIt-SNE to the latest version of FIt-SNE which implements Dmitry's fix. 

Please re-open if you are still having this problem.

**Comment by CamiloMartinezM** [comment]
I still get this error if I try to install from pypi. If I try to compile it with g++, I get the following:

```
In file included from src/tsne.cpp:40:
src/nbodyfft.h:7:10: fatal error: fftw3.h: No such file or directory
    7 | #include <fftw3.h>
      |          ^~~~~~~~~
compilation terminated.
In file included from src/nbodyfft.cpp:5:
src/nbodyfft.h:7:10: fatal error: fftw3.h: No such file or directory
    7 | #include <fftw3.h>
      |          ^~~~~~~~~
compilation terminated.
```

This [question](https://stackoverflow.com/questions/63248212/how-to-supply-fftw-path-to-g-for-installation-of-fit-sne) as asked 9 months ago on stackoverflow, showing the same behaviour, but no one could answer. Thank you in advance for looking into this.

**Comment by rained1989** [comment]
That because you did not have fftw3. Try to install it and add -I/path/to/include/ -L/path/to/lib/ to FIt-SNE install command.
