### ISSUE TITLE
Huge memory problems as number of iteration increases

### ISSUE THREAD

**Issue by alexandreday** [KlugerLab/pyFIt-SNE#5]
I ran the code for 5000 iterations and rapidly ran out of memory.
It seems that deallocation is not done properly at every step. My dataset is 60000x20.
After 1000 iterations my memory requirement was about 3GB.
After 3000 iterations is was about 40 GB ! I am running this on OSX 10.13.4 and python3.6.

**Comment by linqiaozhi** [comment]
This appears to be the same issue as KlugerLab/FIt-SNE#10. It is very likely to be a memory leak, as you pointed out. It might be a very simple fix: not sure if you or anyone else might have the time to recompile with the proper flags and run Valgrind on it and see if a memory leak is clear. 

I am actually traveling (for my honeymoon) until Sunday so it is difficult for me to address it this myself. It will be a high priority for me upon my return, but if someone has the chance to look at it before then, I would gladly accept a pull request.

**Comment by linqiaozhi** [comment]
I found the memory leak I believe to causing the problem, and I fixed it in a [fork](https://github.com/linqiaozhi/FIt-SNE/commit/983345e073388f1a280107d2dfe93f5071994bd7) of the Matlab/R repository. It is just a one-line change, so if you want to try it in the Python version, please go ahead, the file is exactly the same there.

Once I have more time to test it, I will pull request and also update the PyPI package.

**Comment by linqiaozhi** [comment]
The most recent commit fixes the memory leak, and now the latest version on PyPI (0.2.3) is also updated. Please try it again with 5000 iterations and let me know if the issue persist (can reopen if it is not resolved).
